function [hfc, T] = get_hfc(song, winLength, winStep)

winLengthInSamples = ceil(winLength*song.SampleRate);
stepInSamples = ceil(winStep*song.SampleRate);

[S,F,T] = spectrogram(song.UserData, ...
                      winLengthInSamples, ... 
                      winLengthInSamples-stepInSamples, ...
                      [], ...
                      song.SampleRate);
                  
hfc = abs(S.')*(F);
